# Generated by Django 5.1.5 on 2026-04-10 14:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('generated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-generated_at',),
                'indexes': [models.Index(fields=['user', 'generated_at'], name='dashboard_w_user_id_9ec014_idx'), models.Index(fields=['user', 'period_start', 'period_end'], name='dashboard_w_user_id_10673f_idx')],
            },
        ),
    ]
