# Generated by Django 5.1.5 on 2026-04-28 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('nutrition', '0004_postworkoutworkflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('post_workout_reminder', 'Post Workout Reminder')], db_index=True, max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_notifications', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_notification', to='nutrition.postworkoutworkflow')),
            ],
            options={
                'ordering': ('is_read', '-created_at'),
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='dashboard_d_user_id_0abd29_idx'), models.Index(fields=['user', 'kind', 'created_at'], name='dashboard_d_user_id_3d4398_idx')],
            },
        ),
    ]
