# Generated by Django 5.1.5 on 2026-04-28 01:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dashboardnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyinsight',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=12),
        ),
        migrations.AddIndex(
            model_name='weeklyinsight',
            index=models.Index(fields=['user', 'period_start', 'period_end', 'language'], name='dashboard_w_user_id_5ed137_idx'),
        ),
    ]
