# Generated by Django 5.1.5 on 2026-04-28 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_weeklyinsight_language_and_more'),
        ('nutrition', '0004_postworkoutworkflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardnotification',
            name='weekly_insight',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_notification', to='dashboard.weeklyinsight'),
        ),
        migrations.AlterField(
            model_name='dashboardnotification',
            name='kind',
            field=models.CharField(choices=[('post_workout_reminder', 'Post Workout Reminder'), ('weekly_insight', 'Weekly Insight')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='dashboardnotification',
            name='workflow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_notification', to='nutrition.postworkoutworkflow'),
        ),
    ]
