# Generated by Django 5.1.5 on 2026-04-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='goal',
            field=models.CharField(choices=[('lose', 'Lose Weight'), ('reduce_fat', 'Reduce Fat'), ('maintain', 'Maintenance'), ('gain', 'Gain Muscle')], default='maintain', max_length=10),
        ),
    ]
