# Generated by Django 5.1.5 on 2026-04-15 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GymRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('exercises', models.JSONField(default=list)),
                ('adjusted_met', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('muscle_groups', models.JSONField(blank=True, default=list)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=60)),
                ('ai_analysis', models.TextField(blank=True, null=True)),
                ('last_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_routines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddField(
            model_name='activitylog',
            name='gym_routine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='activities.gymroutine'),
        ),
        migrations.AddIndex(
            model_name='gymroutine',
            index=models.Index(fields=['user', 'updated_at'], name='activities__user_id_116e35_idx'),
        ),
        migrations.AddIndex(
            model_name='gymroutine',
            index=models.Index(fields=['user', 'name'], name='activities__user_id_afc2fd_idx'),
        ),
    ]
