# Generated by Django 5.1.5 on 2026-04-09 13:13

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('calories_goal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('protein_goal_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('carbs_goal_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fat_goal_g', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255)),
                ('open_food_facts_id', models.CharField(max_length=100)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=8)),
                ('protein_g', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('carbs_g', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('fat_g', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('quantity_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('post_workout', 'Post Workout')], max_length=20)),
                ('logged_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-logged_at',),
            },
        ),
        migrations.CreateModel(
            name='MealRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories_target', models.DecimalField(decimal_places=2, max_digits=8)),
                ('protein_target_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('carbs_target_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fat_target_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('recommended_foods', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-generated_at',),
            },
        ),
    ]
