# Generated by Django 5.1.5 on 2026-04-09 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0002_initial'),
        ('nutrition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailygoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealrecommendation',
            name='activity_log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meal_recommendation', to='activities.activitylog'),
        ),
        migrations.AddConstraint(
            model_name='dailygoal',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_daily_goal_per_user'),
        ),
        migrations.AddIndex(
            model_name='foodlog',
            index=models.Index(fields=['user', 'logged_at'], name='nutrition_f_user_id_d3c183_idx'),
        ),
        migrations.AddIndex(
            model_name='foodlog',
            index=models.Index(fields=['user', 'meal_type'], name='nutrition_f_user_id_674648_idx'),
        ),
    ]
