# Generated by Django 5.1.5 on 2026-04-23 02:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlog',
            name='nutrition_source',
            field=models.CharField(choices=[('usda', 'USDA'), ('open_food_facts', 'Open Food Facts'), ('ai', 'AI estimate'), ('manual', 'Manual entry')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='source_item_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='source_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='foodlog',
            index=models.Index(fields=['user', 'nutrition_source'], name='nutrition_f_user_id_c0c89c_idx'),
        ),
    ]
