# Generated by Django 5.1.5 on 2026-04-28 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_gymroutine_activitylog_gym_routine_and_more'),
        ('nutrition', '0003_foodlog_nutrition_source_foodlog_source_item_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostWorkoutWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('reminder_due', 'Reminder Due')], db_index=True, default='pending', max_length=20)),
                ('reminder_due_at', models.DateTimeField(db_index=True)),
                ('reminder_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_message', models.TextField(blank=True, default='')),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_workout_workflow', to='activities.activitylog')),
                ('completed_by_food_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_post_workout_workflows', to='nutrition.foodlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_workout_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('status', 'reminder_due_at', '-created_at'),
                'indexes': [models.Index(fields=['user', 'status', 'reminder_due_at'], name='nutrition_p_user_id_f5b410_idx'), models.Index(fields=['user', 'created_at'], name='nutrition_p_user_id_a423f3_idx')],
            },
        ),
    ]
